import GLib from 'gi://GLib';
import Meta from 'gi://Meta';
import Shell from 'gi://Shell';
import St from 'gi://St';

const Clipboard = St.Clipboard.get_default();

// Listens for clipboard owner-changed events on the GNOME display selection.
//
//   - SELECTION_CLIPBOARD is always observed (the standard "Ctrl-C" target).
//   - SELECTION_PRIMARY is observed only when the `process-primary-selection`
//     GSetting is true.
//
// Each observed event reads the new text and submits it to the ringboard
// server via SubprocessClient.add. UI state is not touched: the menu fetches
// fresh from the server when opened.
export class ClipboardIntake {
  constructor(client, settings) {
    this._client = client;
    this._settings = settings;
    this._enabled = false;
    this._selection = null;
    this._ownerChangedId = 0;
    this._settingsChangedId = 0;
    this._processPrimary = false;

    // Counter incremented when the extension itself writes to the clipboard
    // (e.g. paste-on-selection). Each owner-changed signal fired by our own
    // write decrements this; positive value suppresses one event.
    this._debouncing = 0;
  }

  enable() {
    if (this._enabled) return;
    this._enabled = true;

    this._selection = Shell.Global.get().get_display().get_selection();
    this._ownerChangedId = this._selection.connect(
      'owner-changed',
      (_sel, type, _source) => this._onSelectionChanged(type),
    );

    this._processPrimary = this._settings.get_boolean('process-primary-selection');
    this._settingsChangedId = this._settings.connect(
      'changed::process-primary-selection',
      () => {
        this._processPrimary = this._settings.get_boolean('process-primary-selection');
      },
    );
  }

  disable() {
    if (!this._enabled) return;
    this._enabled = false;

    if (this._selection && this._ownerChangedId) {
      this._selection.disconnect(this._ownerChangedId);
    }
    if (this._settings && this._settingsChangedId) {
      this._settings.disconnect(this._settingsChangedId);
    }
    this._selection = null;
    this._ownerChangedId = 0;
    this._settingsChangedId = 0;
  }

  // Suppress the next owner-changed signal generated by our own writes.
  // Call once per St.Clipboard.set_text we issue.
  expectOwnWrite() {
    this._debouncing += 1;
  }

  _onSelectionChanged(selectionType) {
    if (!this._enabled) return;

    if (selectionType === Meta.SelectionType.SELECTION_CLIPBOARD) {
      // accepted
    } else if (selectionType === Meta.SelectionType.SELECTION_PRIMARY) {
      if (!this._processPrimary) return;
    } else {
      return; // SELECTION_DND etc.
    }

    if (this._debouncing > 0) {
      this._debouncing -= 1;
      return;
    }

    if (this._settings.get_boolean('private-mode')) {
      return;
    }

    const stType =
      selectionType === Meta.SelectionType.SELECTION_PRIMARY
        ? St.ClipboardType.PRIMARY
        : St.ClipboardType.CLIPBOARD;

    Clipboard.get_text(stType, (_clip, text) => {
      if (typeof text !== 'string' || text.length === 0) return;
      let payload = text;
      if (this._settings.get_boolean('strip-text')) {
        payload = payload.trim();
      }
      if (payload.length === 0) return;
      this._client.add(payload).catch(e => {
        console.warn(`ringboard: client.add failed: ${e.message}`);
      });
    });
  }
}
